- hosts: 172.31.10.8
  tasks:
   - name: install apache server
     yum:
       name: httpd
       state: present
   - name: copy code to the remove machine
     copy:
       src: index.html
       dest: /var/www/html
   - name: start apache
     service:
       name: httpd
       enabled: yes
       state: started
       
       
       
